---
version: "3.8"

services:
  drone-server:
    image: drone/drone
    ports:
      - 7000:80
      - 7001:443
    volumes:
      - /var/lib/drone/:/data
      - ${TLS_CERT_HOST_PATH}:${TLS_CERT_DOCKER_PATH}
      - ${TLS_KEY_HOST_PATH}:${TLS_KEY_DOCKER_PATH}
    restart: always
    environment:
      - DRONE_OPEN=false
      - DRONE_ADMIN=${USER}
      - DRONE_SERVER_HOST=${DRONE_HOST}
      - DRONE_SERVER_PROTO=https
      - DRONE_GITHUB=true
      - DRONE_GITHUB_CLIENT_ID=${DRONE_GITHUB_CLIENT_ID}
      - DRONE_GITHUB_CLIENT_SECRET=${DRONE_GITHUB_CLIENT_SECRET}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_TLS_CERT=${TLS_CERT_DOCKER_PATH}
      - DRONE_TLS_KEY=${TLS_KEY_DOCKER_PATH}
...
